apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: sample-app
        image: 105673812211.dkr.ecr.ap-southeast-2.amazonaws.com/sample-app:v1
        ports:
        - containerPort: 5000
